# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Nation Branding Now
author: Andrew Papenheim
timezone: America/Montreal

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-doc

theme_config:
  favicon: images/favicon.ico
  google_analytics: UA-145856346-1
  support:
    link_url: 'TK'
    text: 'Content on NationBrandingNow is non-exhaustive and compiled using best-available public information. Nothing on this page should be taken as an endorsement of or affiliation with any government. NBN does not own and does not imply to own the visual assets described. Be aware that protected marks may have stringent <a href="/guide/use.html">use restrictions</a>.<br><br>If you have a comment or question about what you saw today, please'
    link_text: 'contact the editorial team.'
    navigation: false
    navigation_label: 'SUPPORT'

ignore:
  # development only: ignore sub node_modules when `npm link hexo-theme-doc`
  - '**/node_modules/**/*node_modules'
